packages: null

catalog:

catalogMode: strict

cleanupUnusedCatalogs: true

enablePrePostScripts: true

minimumReleaseAge: 2880

strictDepBuilds: true

blockExoticSubdeps: true

trustPolicy: no-downgrade

allowBuilds:

shellEmulator: true
